### ISSUE TITLE
More details about exercises of module 2

### ISSUE THREAD

**Issue by jsanz** [CartoDB/carto-workshop#42]
Module 2 is getting a good set of exercises. We should put more info about them in the front page, at least these bits:

* Difficulty
* Analysis used
* If they are related to any vertical maybe?

@CartoDB/support any ideas on how to do this are welcome. I'm thinking on just a table

**Comment by ernesmb** [comment]
I think a table is fine for the number of exercises we have now

**Comment by ramiroaznar** [comment]
I think difficult, analysis, datasets, vertical would be great. :-)

**Comment by ztephm** [comment]
+ 1 those 3 categories & table - table's quickest to scan & understand.

**Comment by jsanz** [comment]
Thanks, I'll try to do this next week :raised_hands:
