### ISSUE TITLE
Twitter exercise

### ISSUE THREAD

**Issue by jsanz** [CartoDB/carto-workshop#55]
Create an exercise on rendering a Twitter map using the data already gathered [here](https://github.com/CartoDB/carto-workshop/blob/master/01-builder-visualization/exercises/maps/twitter_pride.csv.gz).

You need to do a branch, create the exercise and the propose a PR with the `.carto` file, the exercise and any other resource updated in the repository. Let me know if you need help on this.

**Comment by alexsroth** [comment]
@jsanz is there any criteria for this other than use the data provided?

**Comment by jsanz** [comment]
It's in the visualization module so you shouldn't do any análisis or sql
hack, just a plain animated map with some meaningful widgets. Michelle can
give you some guidelines

--
Jorge Sanz
CARTO - Predict through location

Sent from my phone, excuse my brevity.

El 6 jul. 2017 20:08, "alexsroth" <notifications@github.com> escribió:

@jsanz <https://github.com/jsanz> is there any criteria for this other than
use the data provided?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CartoDB/carto-workshop/issues/55#issuecomment-313475215>,
or mute the thread
