### ISSUE TITLE
X-lite problems

### ISSUE THREAD

**Issue by abelgibert** [CartoDB/carto-workshop#63]
Hello!

I just got an email from a Lead mentiong that my calls from x-lite show up like "Private Number" and most of the people do not pick up such numbers.

Can something be done?

Additionally, I do get some telephone numbers that it wont let me call for no reason at all.

Thanks!

**Comment by acienfuegos** [comment]
Hey!

I will ping you to review this, but I have moved this issue here: https://github.com/CartoDB/companystuff/issues/1637

The right repo is `companystuff`, I dont know why did you open this in `carto-workshop` :eyes:
