### ISSUE TITLE
Recover exercise final map

### ISSUE THREAD

**Issue by jsanz** [CartoDB/carto-workshop#70]
At the end of this exercise the link is not working

https://github.com/CartoDB/carto-workshop/blob/master/01-builder-visualization/exercises/centroids.md

We should have this map on the `builder-demo` account for stability.

**Comment by ramiroaznar** [comment]
I found the map on `builder-demo` account:

https://team.carto.com/u/builder-demo/builder/e5335529-b27f-4f76-bd68-59959a27a966/embed

Going to change it directly in master.
